spring:
  datasource:
    url: jdbc:mysql://quantitydb.c5cuacokmjgk.ap-south-1.rds.amazonaws.com/qma_db
    username: admin
    password: password123

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: ${JWT_SECRET}	
server:
 port: 8082